### ISSUE TITLE
Add endpoint for UI to retrieve git branch/tag/commits

### ISSUE THREAD

**Issue by rawagner** [stolostron/cluster-templates-operator#94]
We already provide endpoint for UI to allow communication with helm repositories https://github.com/stolostron/cluster-templates-operator/blob/main/bridge/server.go#L13

we need add another one for git repositories. It also needs to support private git repositories configured via argocd secrets

**Comment by machacekondra** [comment]
@rawagner For helm we currently return the `index.yaml` what type of information we want to fetch from git to show to the "user"?

**Comment by rawagner** [comment]
branches and tags
